### ISSUE TITLE
Clean up Test Run interface

### ISSUE THREAD

**Issue by ezys** [SkyTruth/CrowdProjects#19]
Looking good.  A few more technical details to clean up.

![screen shot 2014-12-29 at 9 42 01 am](https://cloud.githubusercontent.com/assets/5930891/5572930/0eb26820-8f73-11e4-9883-ac7573ad6a26.png)

- [x] Remove text about expanding the task box. No longer a function.
- [x] Move the bubble about "revisiting the tutorial" over to the left so that it lines up with the referenced button. 

And please add a couple explanatory bubbles about the new buttons in the task bar. Image below is for reference, but ignore the color and exact placement. Keep consistent with the other speech bubbles.

![screen shot 2014-12-29 at 4 07 33 pm](https://cloud.githubusercontent.com/assets/5930891/5573341/39dfb24a-8f79-11e4-9b38-4578f800dfa2.png)

- [x] Submit Button: "Click to trace the pad, double-click to finish. Then click here to submit and go on to the next task."

- [x] Undo Buttons: "Oops! Click one of these buttons to start over or undo the last click."

- [x] Not a pad/Don't know: "Don’t see a pad, or just don’t know what that is? Click one of these buttons."

**Comment by redhog** [comment]
Done in https://github.com/SkyTruth/pybossa_tools/commit/82347eb09122f445626854b05cd47cf4d6f290ba
