### ISSUE TITLE
Test FrackFinder App

### ISSUE THREAD

**Issue by ezys** [SkyTruth/CrowdProjects#21]
Kick the tires on the latest version of the Pad Tracer.

http://crowd.dev.skytruth.org/app/k-test4/newtask

Record any bugs or things that aren't very clear.

**Comment by ezys** [comment]
@redhog Which app has the most recent version of the tutorial for FrackFinder OH?

**Comment by geowurster** [comment]
@Yolandeezy please check the output from the tasks as well.  We made some changes and I want to be sure that everything is correct.  I'm pretty sure it is but want a second set of eyes.
