### ISSUE TITLE
Don't allow the user to submit if they have not closed a polygon.

### ISSUE THREAD

**Issue by Yolandeezy** [SkyTruth/CrowdProjects#25]
If the user clicks twice on the map to start drawing a polygon, does not double-click to close, and clicks done then the subsequent task-run does not contain any geometry but has a `selection` of `done`.

The user should not be allowed to submit a task if there is an open geometry.  Instead they should be presented with an error stating they have to close polygons before submitting.

**Comment by redhog** [comment]
Done in https://github.com/SkyTruth/pybossa_tools/commit/c1b41fb2d0a8b811c67c336f9d9464cef0075bb4

**Comment by redhog** [comment]
It's impossible / hard to detect an unfinished geometry, http://dev.openlayers.org/docs/files/OpenLayers/Control/DrawFeature-js.html does not seem to have any api for that, so right now I'm just detecting there being at least one finished geometry. Hope that's good enough...
