### ISSUE TITLE
Unknown condition where task runs don't have geometry or a selection

### ISSUE THREAD

**Issue by Yolandeezy** [SkyTruth/CrowdProjects#26]
There is an unknown condition where the output `task_run['info']` dictionary doesn't have a `shapes` or `selection` key.  See task run with id `91666`.

**Comment by redhog** [comment]
Which app is this in (url)? Do you know what was done to generate this / any ideas how to repeat it?

**Comment by geowurster** [comment]
http://crowd.dev.skytruth.org/app/k-test4/

**Comment by geowurster** [comment]
We couldn't figure out how to recreate it.

**Comment by redhog** [comment]
To recreate the bug:
Click the icon on the submit button, not the text.

Bugfixed in https://github.com/SkyTruth/pybossa_tools/commit/ad2ccff7ab281aa4727cdcf6517df87df0013c2d
