### ISSUE TITLE
Export Data from FrackFinder Wellpad Tracer

### ISSUE THREAD

**Issue by ezys** [SkyTruth/CrowdProjects#28]
- [ ] Write conversion utility to convert tasks and taskruns to an OGR supported format
- [ ] Convert data and upload to Github along side previous exports
- [ ] Send link to @ezys

**Comment by Yolandeezy** [comment]
@ezys is the data conversion tool on another ticket? If so, could you link to that ticket so that I know when it is ready?

**Comment by ezys** [comment]
Need to get this moving again. Is is possible to complete this ticket by the end of the week?

**Comment by Yolandeezy** [comment]
@ezys Not if I have to be the person who does it. I need to take some time off of work to un-fry my brain and catch up on some school assignments
Maybe ask @geowurster

**Comment by geowurster** [comment]
As per a discussion with David, he needs data by 3/11/15

**Comment by geowurster** [comment]
@ezys - https://github.com/SkyTruth/CrowdProjects/tree/master/Data/FrackFinder/OH/2010-2013/Pad-Delineator/transform

**Comment by ezys** [comment]
You rock @geowurster  and the output totally doesn't suck. :) Thanks.
