### ISSUE TITLE
Generate Shapefiles Aggregated from Results of FrackFinder OH: Wellpad Tracer

### ISSUE THREAD

**Issue by ezys** [SkyTruth/CrowdProjects#30]
Compute two "geometric means" from the raw data produced by the FrackFinder OH: Wellpad Tracer frackathon, and export the results as a shapefile for QA/QC. Use a raster resolution of 1 meter for now, unless we find there are issues with how that looks.

- [x] Export a shapefile derived from the true geometric mean
- [x] Export a shapefile derived from a more inclusive composite that tries to include up to 80% overlap.  

The data is stored in this repo: https://github.com/SkyTruth/CrowdProjects/tree/master/Data/FrackFinder/OH

Kevin has written up some or all of the code for computing a mean for this here: http://nbviewer.ipython.org/gist/geowurster/661c43a8a7b5de2e499f

**Comment by geowurster** [comment]
@ezys @Yolandeezy the algorithm we really want is conflation - the method in that IPython notebook will probably get us workable results but its not technically the correct way to do it.  I have not found a computational geometry with a conflation algorithm that will play nicely with our stack but its worth looking a bit more.
