### ISSUE TITLE
Compare FrackFinder OH Exports

### ISSUE THREAD

**Issue by ezys** [SkyTruth/CrowdProjects#31]
Dependent on #30 

Compare the quality of the true mean with the 80% mean. 

If they both appear to reasonably reflect reality, then we will proceed with a comparison where you digitize the same sites yourself and compare the overlap between your results and the results of the crowd.

- [x] Select number of sites to verify
- [x] Digitize your own polygons to compare to the crowd results
- [x] Quantify difference between your control and the crowd composites

If one of the exports grossly misrepresents what we see in the imagery, we will tweak the way we build the shapefiles so we can produce and compare two reasonably accurate datasets.

**Comment by Yolandeezy** [comment]
|   Agreement    | Area of Comparison Set |  Intersecting Area  |% Error by Omission    | Union Area | % Error by Inclusion  |	Combined Error |
| --------------- | :--------------: | :---------------: | :-----------------: | :------------------: | :-------------: | -----------:|
|**mean**|*1,702,634*|	1,439,900|	15.4%|	1,711,741|	0.5%|	16%|
|**60 %**|	*1,702,634*|     1,536,858|   	  9.7%|     1,720,804|	1.1%|	11%|
|**70 %**| *1,702,634*|     1,511,461|	11.2%|	1,714,156|	0.7%|	12%|
|**80 %**|	*1,702,634*|     1,478,018|	13.2%|	1,709,879|	0.4%|	14%|

**Comment by Yolandeezy** [comment]
Now Dependent on #32 

% Error by Omission is high because polygons are somehow being thrown out during the reduction process. I'm un-checking the last box on the to-do list because it needs to be redone once this issue is resolved.

**Comment by Yolandeezy** [comment]
|   Agreement    | Area of Comparison Set |  Intersecting Area  |% Error by Omission    | Union Area | % Error by Inclusion  |	Combined Error |
| --------------- | :--------------: | :---------------: | :-----------------: | :------------------: | :-------------: | -----------:|
|**mean**|  *1,702,634*|    1,542,135|	  9.4%|	1,715,593|	0.8%|	10%|
|**40%**|    *1,702,634*|    1,660,816|	  2.5%|	1,755,314|   	3.1%|	  6%|
|**50%**|    *1,702,634*|	   1,644,593|	  3.4%|	1,733,248|	1.8%|	  5%|
|**60%**| 	   *1,702,634*|    1,551,616|   	  8.9%|     1,722,303|	1.2%|	10%|
|**70%**|    *1,702,634*|    1,524,863|	10.4%|	1,714,980|	0.7%|	11%|
|**80%**|	   *1,702,634*|    1,490,030|	12.5%|	1,710,329|	0.5%|	13%|

*Area in m^2*
