### ISSUE TITLE
Satellite polygon not processed by pond-reducer.py 

### ISSUE THREAD

**Issue by Yolandeezy** [SkyTruth/CrowdProjects#32]
On certain sites with multiple polygons, satellite polygons get thrown out by pond-reducer.py despite meeting the cut off for % agreement.

i.e....
In [pad_delineator output](https://github.com/SkyTruth/CrowdProjects/blob/master/Data/FrackFinder/OH/2010-2013/Pad-Delineator/transform/pad_delineations.shp), `task_id: 30116` has 3 neighboring polygons (two of which are digitized multiple times). The main polygon is digitized 10 times and the larger satellite polygon 7 times. The satellite polygons is not being processed.

**Comment by Yolandeezy** [comment]
pond-reducer.py is now appropriately named *pad*-reducer.py, and it lives in [.../FrackFinder/OH/2010-2013/Pad-Delineator/Processing-Tools/pad-reducer.py](https://github.com/SkyTruth/CrowdProjects/blob/master/Data/FrackFinder/OH/2010-2013/Pad-Delineator/Processing-Tools/pad-reducer.py)

**Comment by geowurster** [comment]
@Yolandeezy Can you provide an example command that produces the behavior?

**Comment by Yolandeezy** [comment]
$ `./Data/FrackFinder/OH/2010-2013/Pad-Delineator/Processing-Tools/pad-reducer.py Data/FrackFinder/OH/2010-2013/Pad-Delineator/transform/pad_delineations.shp Data/FrackFinder/OH/2010-2013/Pad-Delineator/transform/50percent-agreement-test.shp --agreement 0.50`

I'd recommend a sub folder to drop your test file in, of course, but I can't seem to push the one I created.

**Comment by geowurster** [comment]
@Yolandeezy I moved `pad-reducer.py` from `Processing-Tools` to `bin`.

**Comment by geowurster** [comment]
@Yolandeezy Try again.  There was an issue with how the bounding box was being computed.
