### ISSUE TITLE
Finalize Methodology for Pad Delineator Results

### ISSUE THREAD

**Issue by ezys** [SkyTruth/CrowdProjects#34]
Finish the write up of the process for generating the pad delineator results, including the table of the errors of omission/inclusion found during the QA/QC process

**Comment by Yolandeezy** [comment]
https://github.com/SkyTruth/CrowdProjects/blob/master/Data/FrackFinder/OH/2010-2013/Pad-Delineator/transform/reduced-pads/README.md

This may not be the same layout that Kevin uses but I tried
