### ISSUE TITLE
Find and evaluate permitting data

### ISSUE THREAD

**Issue by Yolandeezy** [SkyTruth/CrowdProjects#35]
- [x] @ezys suggest starting with [WVDEP](https://apps.dep.wv.gov/oog/permitsearch_new.cfm)
- [x] How many horizontal 6a permits are there?
- [ ] How many completed fracturing permits are there?
- [x] What shale formations are active?
- [x] What counties are being fracked?
- [x] How much activity for NAIP years: 2006, 2007, 2009, 2011, 2014 (Do we have enough available data?)
- [ ] Can we cluster wells to sites? 
- [ ] Schedule meeting with @ezys to plan next steps.

**Comment by ezys** [comment]
Checking the boxes doesn't tell us anything. Closing.
