### ISSUE TITLE
How should we serve up the NAIP imagery in Pybossa? 

### ISSUE THREAD

**Issue by ezys** [SkyTruth/CrowdProjects#38]
Is the imagery already in Earth Engine/ some other platform? Or will we have to build our own WMS server?

**Comment by geowurster** [comment]
@ezys I have been told it is in EE, but have not used it.  Will find out when I'm at the EE User Summit in https://github.com/SkyTruth/tasks/issues/403.  How many counties in WV are we looking at?

If we can't use EE to serve the one of these companies may:

1. Mapbox generally tries to display the most up to date basemap + imagery, so they probably only have the most recent NAIP in their aerial basemap, but if they have all of it online, they may have a method for only loading tiles from a specific year.
2. I think CartoDB offers an imagery basemap but probably with the same constraints as above.
3. ESRI has a bunch of basemaps, but with the same constraints as above.
5. Some other hosted service.  There's a whole industry built around selling this kind of product to local GIS offices, so I'm sure some company somewhere can do this for us.  A bit of internet sleuthing would probably turn up a reputable one too.

Alternatively, we're not talking about a lot of imagery so if we get the imagery we can just pay Mapbox or CartoDB or ESRI to host it for us.  If we _really_ have to we can set up our own [Mapserver](http://mapserver.org/) instance, which is an open source WMS server.  It's on us to implement any load balancing, caching, etc. that you get with hosted solutions so this will take a fair amount of human time, especially for styling, which is done through a [`mapfile`](http://mapserver.org/mapfile/).  I think there's a QGIS plugin for translating QGIS style sheets to a Mapserver `mapfile`.

If we end up in a situation where we have to go find the data, I have heard it is available in a [requester pays](http://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html) bucket on `S3`, but have not checked myself (don't have an AWS environment set up).  https://github.com/mapbox/s3pay/issues/1 suggests this is true, but may not be permanent.  I think its the raw 16 bit GeoTIFF's (with NIR!) so the bandwidth fee may be kinda high, but I doubt its more expensive than the human time it would take to manually download everything from NRCS.  The extra size may make it harder to mosaic though.
