### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by ezys** [SkyTruth/CrowdProjects#39]
Is SiteInfo still an active project? For FrackFinder PA, SiteInfo was the source data you listed for all subsequent projects. 

If not an active project, should we go about clustering locations using one of the old tools for SiteInfo? Or just process from scratch using tools in QGIS.

**Comment by geowurster** [comment]
@ezys I joined SkyTruth after FrackFinder was already up and running, so I have no idea what went into prepping the permit data.  I can't find `SiteInfo` in GitHub either.

I clustered the Ohio Tadpole permits with some [Python and the OGR bindings](https://github.com/SkyTruth/CrowdProjects/blob/master/Data/FrackFinder/OH/2010-2013/Tadpole/bin/permits2sites.py), but QGIS may have a clustering tool or plugin by now.  That script is pretty rough and I don't recommend re-using it.

I think `SiteInfo` used [`dbscan`](http://scikit-learn.org/stable/modules/generated/sklearn.cluster.dbscan.html), which is probably the easiest way to do it if the operator knows some Python.
