### ISSUE TITLE
Requirements for Working in Pybossa

### ISSUE THREAD

**Issue by ezys** [SkyTruth/CrowdProjects#40]
What languages do @TwigBeard or @cjthomas730 need to work in to load tasks and set up projects in Pybossa?

Which virtual environment should be used?

Any credentials or permissions that need to be secured to access SkyTruth accounts/past projects?

**Comment by geowurster** [comment]
@ezys Yeah we're running some hacked together Pybossa branch that's like 2 years old.  I think @redhog hit some bugs he had to fix, but I don't think those patches were ever submitted upstream.  [`pybossa_tools`](https://github.com/SkyTruth/pybossa_tools) contains the project files (Tadpole, padmapper, etc) and `createTasks.py`, which is what we use to push tasks to the server.  Looks like there's a sample command in the [`HOWTO.txt`](https://github.com/SkyTruth/pybossa_tools/blob/master/HOWTO.txt#L21-L30) file.  I'm not sure what the server URL is, but the API key is for the admin account.  I just sent you the PW and account name.

The dependencies for `pybossa_tools` are pretty crusty, but it looks like we can probably still install it locally in a Python virtual environment with:

```console
$ git clone https://github.com/SkyTruth/pybossa_tools
$ cd pybossa_tools
$ pip install -r requirements.txt
```

And then I guess as long as you have the virtual env enabled and you're inside the `pybossa_tools` dir on your machine you can do `./createTasks.py`?  It's gonna take some experimentation, but we can't do much without tasks to test, so we need the imagery source and permits first.
